name: 15-minute-cron
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - name: cron job
        shell: bash        
      - run: |
          npm install        
          chmod +x .github/timeout.sh        
          bash .github/timeout.sh
          git config user.email "tanviralamshuvo@gmail.com"
          git config user.name "tanvir-ux"          
          git commit -am "Automated crawling"
          git push 

          
        
        
          
          