name: 15-minute-cron
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - name: cron job
        shell: bash      
      - run:  npm install        
      - run:  chmod +x .github/timeout.sh        
      - run:  bash .github/timeout.sh
      - run:  git config user.email "tanviralamshuvo@gmail.com"
      - run:  git config user.name "tanvir-ux"          
      - run:  git commit -am "Automated crawling"
      - run:  git push 

          
        
        
          
          