name: 15-minute-cron
on:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1      
      - name: cron job
        shell: bash
        run: chmod +x .github/timeout.sh        
      - run: .github/timeout.sh
    

    
          
        
        
          
          